language: cpp
sudo: false

notifications:
email: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: CXX_EVAL="g++-7" CC_EVAL="gcc-7" BUILD_TYPE='Release'

script:   
- cmake -H. -B_build
- cmake --build _build
- cd _build
- ./pack file.json
- cat file.json
- ./unpack file.json